### ISSUE TITLE
TAG Contributor Strategy Review

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/community#14]
We met some lovely people from TAG Contributor Strategy at KubeCon and they mentioned that they do [governance](https://github.com/cncf/tag-contributor-strategy/tree/main/governance) reviews.

I'm not sure of the exact process, but it seems like a great resource so we can get another pair of eyes on what we've done here!

This issue is for tracking that process.

**Comment by maelvls** [comment]
I've invited cert-manager maintainers to come to today's TAG contributor strategy governance WG today. We already started the conversation on Slack: https://cloud-native.slack.com/archives/CT6CWS1JN/p1711646001645409.

TAG contributor strategy meeting notes: https://docs.google.com/document/d/1252lARpe1KYv_MIy4MHQpnRRyEs5LHOQoJ5JgOwksfs/edit#bookmark=id.ysghg2tca23x

**Comment by maelvls** [comment]
The meeting went super well. My notes:

- Josh and Dawn (TAG contributor strategy) said that they didn't realize that cert-manager had been able to get a maintainer from outside Venafi. To them, it showed that the cert-manager project has a "path" for people to become maintainers, which was the main concern they had coming to the meeting.
- To the question "what power do we give to steering committee members?", steering the roadmap is a power we can give. No need to find other areas (such as branding, conformance tests, etc as mentioned previously) to give to steering committee.
- The main concern around the roadmap (and why it's good to have a steering committee to have power on) is that Venafi's roadmap and cert-manager's roadmap may be confused as the same. The project needs its own roadmap, separate from Venafi's.
- A good read to build a vendor-neutral open roadmap: https://contribute.cncf.io/maintainers/community/contributor-growth-framework/open-source-roadmaps/ written by Riaan Kleinhans.
- Riaan is a technical project manager who offered help in implementing the project board roadmap.
- The first steering committee meeting will take place on 9 May 2024. Erik, one of the members of the steering committee, said he was very interested to work on the roadmap during that meeting. I'll report back here once it's done.

**Comment by maelvls** [comment]
I see that there is an item "Reach out for TAG assessment TAG-Contrib-Strategy" in https://github.com/cncf/toc/issues/1306. Do you think the call we had yesterday with Josh and Dawn counts as an assessment? @kgamanji
