### ISSUE TITLE
REQUEST: New membership for @SpectralHiss

### ISSUE THREAD

**Issue by SpectralHiss** [cert-manager/community#20]
### GitHub Username

SpectralHiss

### Requirements

- [X] I have reviewed the [cert-manager Code of Conduct](https://github.com/cert-manager/cert-manager/blob/master/CODE_OF_CONDUCT.md)
- [X] I have reviewed the guidelines in [the contributing page](https://cert-manager.io/docs/contributing/)
- [X] I have [enabled 2FA on my GitHub account](https://help.github.com/articles/about-two-factor-authentication)
- [X] I am an active cert-manager contributor (see GOVERNANCE.md for more info).
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the cert-manager projects

### Sponsor 1

@sgtcodfish

### Sponsor 2

@maelvls

### List of contributions to the cert-manager project

PRs Authored:
OtherName feature:
https://github.com/cert-manager/cert-manager/pull/6404
https://github.com/cert-manager/cert-manager/pull/6620
https://github.com/cert-manager/website/pull/1378

LDAP RDN support in LiteralSubject:
https://github.com/cert-manager/cert-manager/pull/5587

Issues responded to:
https://github.com/cert-manager/cert-manager/issues/4144
https://github.com/cert-manager/cert-manager/issues/6150
https://github.com/cert-manager/cert-manager/issues/6341

Slack conversations:
https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1699551721507549
https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1636449562179000?thread_ts=1636118957.152400&cid=CDEQJ0Q8M
https://kubernetes.slack.com/archives/C4NV3DWUC/p1634810998006500

**Comment by maelvls** [comment]
I am super happy to welcome you onboard!!

**Comment by SgtCoDFish** [comment]
Confirming my sponsorship - Houssem has made some awesome contributions and is always super helpful.

Something we'd discussed previously is adding Houssem as a reviewer for istio-csr, which he's particularly interested in and which definitely needs more eyes on it. I'm happy to also sponsor making that the case, and I'll raise the PR to add him to the OWNERS file in that repo!

**Comment by SgtCoDFish** [comment]
@maelvls has sent an invite for @SpectralHiss to join the cert-manager org!

**Comment by SgtCoDFish** [comment]
I raised https://github.com/cert-manager/istio-csr/pull/241 to add Houssem as a reviewer for istio-csr

**Comment by SgtCoDFish** [comment]
I think this is now complete. Welcome Houssem 🎉
