### ISSUE TITLE
Proposing Ian Arsenault for the Steering Committee

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/community#37]
I [recently](https://kubernetes.slack.com/archives/C4NV3DWUC/p1724839163098129) put out a call for people to join the cert-manager steering commitee and Ian Arsenault (https://github.com/ianarsenault) responded.

He confirmed that at his company they run cert-manager in production and he shared the details of the usage - mostly the ACME issuer, which is great as that's what most users are running!

I'm happy to sponsor Ian, and @erikgb and @maelvls both agreed to also sponsor in the cert-manager standup today.

This issue will track Ian's progress. Given that there are vacancies in the Steering Committee, there's no blocker on Ian taking his seat, so this should be simple. The remaining steps are:

- [x] @maelvls to confirm sponsorship in a comment on this issue
- [x] @erikgb to confirm sponsorship in a comment on this issue
- [x] @ianarsenault to confirm he's happy based on the [current STEERING.md](https://github.com/cert-manager/community/blob/822e5f3d0b8a3aaf97e54a3095ff74e6b2d2d45b/STEERING.md) and the upcoming changes in #36

**Comment by FlorianLiebhart** [comment]
👍 awesome, lgtm! :))

**Comment by erikgb** [comment]
Sounds great! Welcome Ian! 👍

**Comment by ssyno** [comment]
Welcome Ian 👍

**Comment by maelvls** [comment]
Hey, I confirm my sponsorship of Ian. Welcome!

**Comment by ianarsenault** [comment]
Hi 👋,  I confirm I'm happy with the current and upcoming changes to steering committee!

Thanks @SgtCoDFish and everyone else!

**Comment by SgtCoDFish** [comment]
Given that all the checks have completed, I've raised #38 to add Ian to the committee (and did a little housekeeping while I was at it). Once that PR merges we'll be done 🚀

**Comment by SgtCoDFish** [comment]
#38 has merged so Ian is officially a member of the Steering Committee! Welcome 🚀 

I'm talking to someone else about joining the SC. If we get them onboarded that sounds like a great reason to have a second SC meeting soon 😁
