### ISSUE TITLE
REQUEST: New membership for @juliocamarero

### ISSUE THREAD

**Issue by juliocamarero** [cert-manager/community#42]
### GitHub Username

@juliocamarero

### Requirements

- [X] I have reviewed the [cert-manager Code of Conduct](https://github.com/cert-manager/cert-manager/blob/master/CODE_OF_CONDUCT.md)
- [X] I have reviewed the guidelines in [the contributing page](https://cert-manager.io/docs/contributing/)
- [X] I have [enabled 2FA on my GitHub account](https://help.github.com/articles/about-two-factor-authentication)
- [X] I am an active cert-manager contributor (see GOVERNANCE.md for more info).
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the cert-manager projects

### Sponsor 1

@erikgb

### Sponsor 2

@SgtCoDFish 

### List of contributions to the cert-manager project

**PRs reviewed / authored** 
- https://github.com/cert-manager/trust-manager/pull/460
- https://github.com/cert-manager/trust-manager/pull/474
- https://github.com/cert-manager/website/pull/1594

**Comment by SgtCoDFish** [comment]
I'm happy to sponsor this - I echo everything Erik said. It's been a pleasure to have Julio here! I'm going to add Julio to the GitHub org now 👍

**Comment by SgtCoDFish** [comment]
I've sent the invitation - welcome Julio 🚀
