### ISSUE TITLE
REQUEST: New membership for erikgb

### ISSUE THREAD

**Issue by erikgb** [cert-manager/community#6]
### GitHub Username

erikgb

### Requirements

- [X] I have reviewed the [cert-manager Code of Conduct](https://github.com/cert-manager/cert-manager/blob/master/CODE_OF_CONDUCT.md)
- [X] I have reviewed the guidelines in [the contributing page](https://cert-manager.io/docs/contributing/)
- [X] I have [enabled 2FA on my GitHub account](https://help.github.com/articles/about-two-factor-authentication)
- [X] I am an active cert-manager contributor (see GOVERNANCE.md for more info).
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the cert-manager projects

### Sponsor 1

@inteon

### Sponsor 2

@SgtCoDFish

### List of contributions to the cert-manager project

PRs authored:

- [cert-manager](https://github.com/cert-manager/cert-manager/pulls?q=author%3Aerikgb+is%3Aclosed+label%3Aapproved)
- [trust-manager](https://github.com/cert-manager/trust-manager/pulls?q=author%3Aerikgb+is%3Aclosed+label%3Aapproved)

Submitted design proposals:

- https://github.com/cert-manager/approver-policy/pull/256

Other:

In addition to the concrete contributions mentioned above, I've been following the cert-manager projects for a long time - actively involved in various threads on cert-manager Slack channels.

I've also been trying to comment on issues/PRs that I feel are within my competence areas. Lately, I have been trying to groom the backlog of trust-manager - which we are in the process of adopting.

Occasional show-up in daily stand-ups and bi-weekly meetings.

**Comment by inteon** [comment]
+1

**Comment by SgtCoDFish** [comment]
Seconded, obvious inclusion to me!

**Comment by inteon** [comment]
Congratulations! I added @erikgb as a member to the cert-manager org.

Please take a look at the Governance documents to figure out what to do next to become a review (if that is something you are interested in).

**Comment by erikgb** [comment]
> Congratulations! I added @erikgb as a member of the cert-manager org.
> 
> Please take a look at the Governance documents to figure out what to do next to become a review (if that is something you are interested in).

Thanks a lot! ❤️ I also have a job, so I will see how much I can get involved. At present, I'm probably not ready for the commitments required by climbing the "ladder".
