### ISSUE TITLE
REQUEST: New membership for @hawksight

### ISSUE THREAD

**Issue by hawksight** [cert-manager/community#7]
### GitHub Username

@hawksight

### Requirements

- [X] I have reviewed the [cert-manager Code of Conduct](https://github.com/cert-manager/cert-manager/blob/master/CODE_OF_CONDUCT.md)
- [X] I have reviewed the guidelines in [the contributing page](https://cert-manager.io/docs/contributing/)
- [X] I have [enabled 2FA on my GitHub account](https://help.github.com/articles/about-two-factor-authentication)
- [X] I am an active cert-manager contributor (see GOVERNANCE.md for more info).
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the cert-manager projects

### Sponsor 1

@maelvls

### Sponsor 2

@SgtCoDFish

## PRs

- https://github.com/cert-manager/cert-manager/pull/6311
- https://github.com/cert-manager/cert-manager/pull/5247

### created

- https://github.com/cert-manager/cert-manager/issues/5108
- https://github.com/cert-manager/cert-manager/issues/5803
- https://github.com/cert-manager/cert-manager/issues/5514
- https://github.com/cert-manager/cert-manager/issues/5171

### Participated

Link to all the issues I've been involved with, eg. a commentor: https://github.com/cert-manager/cert-manager/issues?q=is%3Aissue+commenter%3Ahawksight+

Too many to link here so, here's a screen grab:
![Screenshot from 2023-08-31 12-45-20](https://github.com/cert-manager/community/assets/11051419/ebeb0f70-270b-41c6-a178-d691abf7ee10)

### From other repos besides cert-manger

- https://github.com/cert-manager/website/issues/1262
- https://github.com/cert-manager/website/pull/1248
- https://github.com/cert-manager/website/pull/1212
- https://github.com/cert-manager/cert-manager/pull/5368
- https://github.com/cert-manager/website/pull/1094
- https://github.com/cert-manager/website/pull/1049

## Slacks

(just some recent ones)

- https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1692898220457779
- https://kubernetes.slack.com/archives/C4NV3DWUC/p1692874673460849
- https://kubernetes.slack.com/archives/C4NV3DWUC/p1692724688596379
- https://kubernetes.slack.com/archives/C4NV3DWUC/p1692739238561459
- https://kubernetes.slack.com/archives/C4NV3DWUC/p1692792308464439
- https://kubernetes.slack.com/archives/C4NV3DWUC/p1692801862900769
- https://kubernetes.slack.com/archives/C4NV3DWUC/p1690974859371849

## Quick search

https://github.com/search?q=org%3Acert-manager+commenter%3Ahawksight&type=issues

![Screenshot from 2023-08-31 12-48-56](https://github.com/cert-manager/community/assets/11051419/743a96d0-c1e1-49ec-ac54-daf831428ebc)

**Comment by SgtCoDFish** [comment]
Full disclosure:  @hawksight , @maelvls and I are all employees of Venafi, but @hawksight 's role isn't as tightly tied to cert-manager as Maël's and mine.

He often goes above and beyond to help the project - I've particularly enjoyed his documentation efforts ([this page](https://cert-manager.io/docs/tutorials/getting-started-with-trust-manager/) is something I've been regularly sharing with others because it's so good).

@hawksight also chaired our last biweekly meeting and did an awesome job of it, which isn't the kind of thing which gets captured easily in issues or PRs but is spectacularly helpful.

Strong +1 from me, proud to sponsor.

Aside: Our latest org member @erikgb also spoke favourably about @hawksight 's inclusion in our standup today.

**Comment by maelvls** [comment]
Also +1 for me, I am gladly sponsoring Peter!

**Comment by erikgb** [comment]
+1 from me also - even if I am not listed (nor eligible) as sponsor! 😉

**Comment by maelvls** [comment]
Welcome onboard, Peter!

![Screenshot 2023-09-01 at 11 54 04](https://github.com/cert-manager/community/assets/2195781/c2f32df1-bbb7-4953-9f9c-e4892680ce32)

**Comment by hawksight** [comment]
![Screenshot from 2023-09-01 11-13-03](https://github.com/cert-manager/community/assets/11051419/050e1c4f-d944-452a-b9b9-004df7ace279)

I am indeed now a member! :tada:
