### ISSUE TITLE
REQUEST: New membership for FlorianLiebhart

### ISSUE THREAD

**Issue by FlorianLiebhart** [cert-manager/community#8]
### GitHub Username

@FlorianLiebhart

### Requirements

- [X] I have reviewed the [cert-manager Code of Conduct](https://github.com/cert-manager/cert-manager/blob/master/CODE_OF_CONDUCT.md)
- [X] I have reviewed the guidelines in [the contributing page](https://cert-manager.io/docs/contributing/)
- [X] I have [enabled 2FA on my GitHub account](https://help.github.com/articles/about-two-factor-authentication)
- [X] I am an active cert-manager contributor (see GOVERNANCE.md for more info).
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the cert-manager projects

### Sponsor 1

@maelvls

### Sponsor 2

@inteon

### List of contributions to the cert-manager project

PR authored: https://github.com/cert-manager/cert-manager/pull/5003

**Comment by maelvls** [comment]
I am gladly sponsoring Florian for joining the organization. Florian designed and implemented an important feature of the ACME issuer.

**Comment by inteon** [comment]
+1

**Comment by maelvls** [comment]
Welcome to the cert-manager org, Florian!!

![Screenshot 2023-09-07 at 18 40 48](https://github.com/cert-manager/community/assets/2195781/23b25660-5dab-4224-a92c-bbe998bf06c1)

**Comment by FlorianLiebhart** [comment]
Oh wow, thanks a lot @maelvls, just accepted it :-) :-)
