### ISSUE TITLE
REQUEST: New membership for jsoref

### ISSUE THREAD

**Issue by jsoref** [cert-manager/community#9]
### GitHub Username

jsoref

### Requirements

- [X] I have reviewed the [cert-manager Code of Conduct](https://github.com/cert-manager/cert-manager/blob/master/CODE_OF_CONDUCT.md)
- [X] I have reviewed the guidelines in [the contributing page](https://cert-manager.io/docs/contributing/)
- [X] I have [enabled 2FA on my GitHub account](https://help.github.com/articles/about-two-factor-authentication)
- [X] I am an active cert-manager contributor (see GOVERNANCE.md for more info).
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the cert-manager projects

### Sponsor 1

@maelvls

### Sponsor 2

@inteon

### List of contributions to the cert-manager project

https://github.com/cert-manager/cert-manager/pulls?q=is%3Apr+author%3Ajsoref+is%3Aclosed

**Comment by maelvls** [comment]
Hey, Josh! Happy to see you join the cert-manager org!! I am happy to sponsor Josh's GitHub membership.

**Comment by inteon** [comment]
+1
Great to officially add you to the cert-manager organisation!

**Comment by maelvls** [comment]
Welcome, @jsoref!
![Screenshot 2023-09-11 at 17 27 07](https://github.com/cert-manager/community/assets/2195781/f5732fd1-e90a-475d-989c-409f83cc8d86)
